version: '3'

services:
  web:
    container_name: portfolio-back
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - ./uploads:/home/app/uploads
  mongo:
    container_name: portfolioDB
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eze
      - MONGO_INITDB_ROOT_PASSWORD=password
